name: Format, Lint, Test

on:
  push:
    branches: [main]

jobs:
  fmt-lint-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint
      
      - name: Run tests
        run: deno test --allow-all
